# Generated by Django 4.2.30 on 2026-09-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_security_id', models.CharField(max_length=64, unique=True)),
                ('ticker_symbol', models.CharField(blank=True, max_length=20)),
                ('cusip', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('security_type', models.CharField(choices=[('equity', 'Equity'), ('etf', 'ETF'), ('mutual fund', 'Mutual Fund'), ('cash', 'Cash'), ('fixed income', 'Fixed Income'), ('derivative', 'Derivative'), ('other', 'Other')], default='other', max_length=20)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('close_price_date', models.DateField(null=True)),
                ('iso_currency_code', models.CharField(default='USD', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_investment_transaction_id', models.CharField(max_length=64, unique=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('fee', 'Fee'), ('transfer', 'Transfer'), ('cancel', 'Cancel')], max_length=20)),
                ('subtype', models.CharField(blank=True, max_length=40)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to='accounts.account')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.security')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('source', models.CharField(choices=[('plaid_sync', 'Plaid sync'), ('backfilled_yfinance', 'Backfilled (yfinance)')], default='plaid_sync', max_length=20)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='investments.security')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('security', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HoldingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.security')),
            ],
            options={
                'indexes': [models.Index(fields=['synced_at'], name='investments_synced__0d64da_idx')],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('institution_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('institution_price_as_of', models.DateField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='accounts.account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.security')),
            ],
            options={
                'unique_together': {('account', 'security')},
            },
        ),
    ]
