# Generated by Django 4.2.30 on 2026-09-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plaid_institution_id', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=64, unique=True)),
                ('keychain_ref', models.CharField(max_length=128, unique=True)),
                ('cursor', models.CharField(blank=True, max_length=256)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('needs_reauth', 'Needs reauth'), ('error', 'Error')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_account_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('official_name', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(choices=[('depository', 'Depository'), ('credit', 'Credit'), ('investment', 'Investment'), ('loan', 'Loan')], max_length=20)),
                ('subtype', models.CharField(blank=True, max_length=30)),
                ('mask', models.CharField(blank=True, max_length=4)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('iso_currency_code', models.CharField(default='USD', max_length=3)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.plaiditem')),
            ],
        ),
    ]
